import { ai, MAIN_MODEL } from "./ai.js";
import { withTimeout } from "./util.js";
import { GUARDRAILS } from "./persona.js";

/* ============================================================================
 * Cooking mode (#15). "Cook me chicken parmesan" / "walk me through carbonara"
 * → a structured recipe the device walks the user through step by step, with an
 * optional per-step timer. Generated by the model; returns null on any failure
 * so the caller can fall back to a normal answer.
 * ==========================================================================*/

export interface RecipeStep {
  instruction: string;
  timerMin?: number; // a hands-off wait (simmer/bake/rest), in minutes
}

export interface Recipe {
  title: string;
  servings: string;   // "4 servings"
  totalTime: string;  // "35 min"
  ingredients: string[];
  steps: RecipeStep[];
}

// Fires only on a clear "guide me through cooking X" intent. NOT a generic "how
// much sugar in a banana" question (that's a normal answer), and NOT "make me a
// schedule" (day plan) or "make a reservation".
export function looksLikeCookingRequest(message: string): boolean {
  const m = message.toLowerCase();
  // Exclude non-food uses of "make/prepare" ("make a reservation", "make a list",
  // "make me a schedule") so they don't get hijacked as recipes.
  if (/\b(reservation|booking|schedule|playlist|appointment|a call|a list|a plan|a decision|a note|a reminder|an? (?:doctor|dentist))\b/.test(m)) return false;
  return (
    /\b(cooking mode|recipe)\b/.test(m) ||
    /\b(walk|guide) me through (?:making|cooking|baking)\b/.test(m) ||
    /\b(?:how (?:do i|to)|teach me (?:to|how to)|help me|let'?s|i want to|i wanna|can you|wanna|show me how to) (?:make|cook|bake|prepare|whip up|fix)\b/.test(m) ||
    /^(?:cook|bake|make|prepare|whip up|fix)\b/.test(m) ||                  // imperative: "cook chicken parm"
    /\b(?:cook|bake|make|prepare|whip up|fix) me\b/.test(m) ||              // "cook me chicken parm"
    /\b(?:cook|make|bake|prepare)\b[^.?!]*\b(?:for (?:dinner|lunch|breakfast)|tonight|step by step)\b/.test(m)
  );
}

// Pull the dish name out of the request for a nicer confirmation line, best-effort.
export function extractDishName(message: string): string {
  const m = message.trim();
  const mm = m.match(
    /\b(?:cooking mode for|recipe for|recipe to make|how (?:do i|to) (?:make|cook|bake)|walk me through (?:making|cooking|baking)|guide me through (?:making|cooking|baking)|teach me (?:to|how to) (?:make|cook|bake)|help me (?:make|cook|bake)|let'?s (?:make|cook|bake)|i want to (?:make|cook|bake)|cook|make|bake|prepare)\s+(.+)/i
  );
  if (!mm) return "";
  return mm[1]
    .replace(/^(?:me|us)\s+/i, "")                                   // "cook ME chicken" → "chicken"
    .replace(/\b(for (?:me|dinner|lunch|breakfast|tonight|two|four|\d+)|tonight|step by step|please|right now)\b.*$/i, "")
    .replace(/[.?!]+$/, "")
    .replace(/^(some|a|an|the)\s+/i, "")
    .trim()
    .slice(0, 60);
}

export async function generateRecipe(
  message: string
): Promise<Recipe | null> {
  const dish = extractDishName(message) || "the dish they asked for";
  const prompt = `${GUARDRAILS}

The user wants to cook. Their request: "${message}"
Produce a clear, accurate, home-cook recipe for ${dish}.

Return ONLY compact JSON, no markdown, no commentary:
{"title":"<dish name, title case>","servings":"<e.g. 4 servings>","totalTime":"<e.g. 35 min>","ingredients":["<qty + item>", ...],"steps":[{"instruction":"<one clear action, present tense>","timerMin":<minutes ONLY for a hands-off wait like simmer/bake/rest, else omit>}]}
Rules:
- 5 to 14 steps, each ONE actionable instruction (≤ 30 words), in order.
- Include "timerMin" ONLY when the step is a genuine hands-off wait (bake 20 min, simmer 10 min, rest 5 min). Never put a timer on active prep ("chop the onion").
- Ingredients: real quantities, ≤ 20 items.
- Be accurate and safe (proper cook temps for meat). If the request is not actually food, return {"title":""}.`;
  try {
    const res: any = await withTimeout(
      ai.models.generateContent({
        model: MAIN_MODEL,
        contents: prompt,
        config: { temperature: 0.4, responseMimeType: "application/json", thinkingConfig: { thinkingBudget: 0 } }
      } as any),
      22000,
      "Recipe"
    );
    const obj = JSON.parse((res.text || "{}").trim());
    if (!obj || !obj.title || !Array.isArray(obj.steps)) return null;
    const steps: RecipeStep[] = obj.steps
      .filter((s: any) => s && typeof s.instruction === "string" && s.instruction.trim())
      .map((s: any) => {
        const step: RecipeStep = { instruction: String(s.instruction).trim().slice(0, 240) };
        const t = Number(s.timerMin);
        if (Number.isFinite(t) && t > 0 && t <= 600) step.timerMin = Math.round(t);
        return step;
      })
      .slice(0, 16);
    if (steps.length < 2) return null;
    const ingredients: string[] = Array.isArray(obj.ingredients)
      ? obj.ingredients.filter((x: any) => typeof x === "string" && x.trim()).map((x: any) => String(x).trim().slice(0, 120)).slice(0, 20)
      : [];
    return {
      title: String(obj.title).slice(0, 80),
      servings: String(obj.servings || "").slice(0, 30),
      totalTime: String(obj.totalTime || "").slice(0, 30),
      ingredients,
      steps
    };
  } catch (error) {
    console.error("Recipe error:", error);
    return null;
  }
}
